import { eventBus, DogIntakeCreatedPayload, DogStatusChangedPayload, ApplicationReceivedPayload, MedicalDuePayload } from '../../events/event-bus';
import { storage } from '../../storage';
import type { TaskRule } from '@shared/schema';

type TriggerType = 'intake' | 'status_change' | 'application_received' | 'medical_due';

async function evaluateAndCreateTasks(
  triggerType: TriggerType,
  context: {
    dogId: string;
    shelterId: string;
    [key: string]: any;
  }
): Promise<void> {
  try {
    const rules = await storage.getActiveTaskRulesByTrigger(triggerType, context.shelterId);
    
    for (const rule of rules) {
      if (matchesConditions(rule, context)) {
        await createTaskFromRule(rule, context);
      }
    }
  } catch (error) {
    console.error(`[Automations Plugin] Error evaluating rules for ${triggerType}:`, error);
  }
}

function matchesConditions(rule: TaskRule, context: Record<string, any>): boolean {
  if (!rule.triggerConditions) return true;
  
  const conditions = rule.triggerConditions as Record<string, any>;
  
  for (const [key, expectedValue] of Object.entries(conditions)) {
    if (context[key] !== expectedValue) {
      return false;
    }
  }
  
  return true;
}

async function createTaskFromRule(rule: TaskRule, context: { dogId: string; shelterId: string }): Promise<void> {
  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + (rule.dueDateOffset || 0));
  
  if (rule.dueTimeOfDay) {
    const [hours, minutes] = rule.dueTimeOfDay.split(':').map(Number);
    dueDate.setHours(hours, minutes, 0, 0);
  }

  await storage.createShelterTask({
    dogId: context.dogId,
    shelterId: context.shelterId,
    title: rule.taskTitle,
    description: rule.taskDescription || undefined,
    taskType: rule.taskCategory || 'custom',
    priority: rule.taskPriority as any,
    status: 'pending',
    dueDate,
    assignedTo: rule.assignToRole || undefined,
    isAutoGenerated: true,
    autoGeneratedFrom: `rule:${rule.id}`,
  });
  
  console.log(`[Automations Plugin] Created task "${rule.taskTitle}" for dog ${context.dogId}`);
}

function handleIntakeCreated(payload: DogIntakeCreatedPayload): void {
  evaluateAndCreateTasks('intake', {
    dogId: payload.dogId,
    shelterId: payload.shelterId,
    pipelineStatus: payload.pipelineStatus,
    intakeRecordId: payload.intakeRecordId,
  });
}

function handleStatusChanged(payload: DogStatusChangedPayload): void {
  evaluateAndCreateTasks('status_change', {
    dogId: payload.dogId,
    shelterId: payload.shelterId,
    previousStatus: payload.previousStatus,
    newStatus: payload.newStatus,
  });
}

function handleApplicationReceived(payload: ApplicationReceivedPayload): void {
  evaluateAndCreateTasks('application_received', {
    dogId: payload.dogId,
    shelterId: payload.shelterId,
    applicationId: payload.applicationId,
    applicationType: payload.applicationType,
  });
}

function handleMedicalDue(payload: MedicalDuePayload): void {
  evaluateAndCreateTasks('medical_due', {
    dogId: payload.dogId,
    shelterId: payload.shelterId,
    medicalRecordId: payload.medicalRecordId,
    recordType: payload.recordType,
  });
}

export function registerRuleEngine(): void {
  eventBus.on('dog.intake_created', handleIntakeCreated);
  eventBus.on('dog.status_changed', handleStatusChanged);
  eventBus.on('application.received', handleApplicationReceived);
  eventBus.on('medical.due', handleMedicalDue);
  console.log('[Automations Plugin] Rule engine registered');
}

export function unregisterRuleEngine(): void {
  eventBus.off('dog.intake_created', handleIntakeCreated);
  eventBus.off('dog.status_changed', handleStatusChanged);
  eventBus.off('application.received', handleApplicationReceived);
  eventBus.off('medical.due', handleMedicalDue);
  console.log('[Automations Plugin] Rule engine unregistered');
}
